---
# WEB SERVER
- hosts: web
  become: yes
  vars_files: 
    - vars/main.yml
    - vars/mysql-users.yml

  roles:
    - web

# DATABASE SERVER
- hosts: db
  become: yes
  vars_files: 
    - vars/main.yml
    - vars/mysql-users.yml

  roles:
    - database